name: campus_track
description: College Attendance & Timetable App (Spark plan, Firestore in-app notifications)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  flutter_riverpod: ^2.5.1
  go_router: ^14.8.1
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  uuid: ^4.4.2
  intl: ^0.19.0
  crypto: ^3.0.3
  google_fonts: ^6.3.0
  shimmer: ^3.0.0
  http: ^1.2.0
  flutter_markdown: ^0.6.14
  google_generative_ai: 0.4.0

  # Firebase packages
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.2.2
  firebase_storage: ^12.2.2

  # --- NEW PACKAGES FOR QR ATTENDANCE ---
  qr_flutter: ^4.1.0      # For generating QR codes on teacher's device
  mobile_scanner: ^5.2.3   # For scanning QR codes on student's device
  secure_application: ^4.1.0
  collection: 1.18.0
  url_launcher: ^6.3.2
  #flutter_windowmanager: ^0.2.0   # For restricting screenshots on Android

dev_dependencies:
  path: ^1.9.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo_foreground.jpg
    - assets/loader.json   # Remove this line if you're not using any Lottie animation

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/logo_foreground.png"
  min_sdk_android: 21
